name: prealignments

pep_version: 2.0.0
sample_table: paper_sample_table.csv

looper:
  output_dir: "$PROCESSED/pepatac/paper/prealignments"

sample_modifiers:
  append:
    pipeline_interfaces: $CODE/pepatac/sample_pipeline_interface.yaml
  derive:
    attributes: [read1, read2]
    sources:
      FQ1: ${SRAFQ}/{srr}_1.fastq.gz
      FQ2: ${SRAFQ}/{srr}_2.fastq.gz
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        macs_genome_size: hs
        prealignments: rCRSd
